# Solving System of Linear Equations using Python - May 2020

<center> 1x + 1y = 35 </center> 
<center> 2x + 4y = 94</center> 
<p> </p> 

$$A = \left[ \begin{array}{ccc} 1 & 1 \\ 2 & 4 \\ \end{array} \right]$$ 
<p></p>
$$X = \left[ \begin{array}{c} x \\ y \\ \end{array} \right]  $$ 
<p></p>
$$B = \left[ \begin{array}{c} 35 \\ 94 \\ \end{array} \right]$$
<p></p>
$$\left[ \begin{array}{ccc} 1 & 1 \\ 2 & 4 \\ \end{array} \right]\left[ \begin{array}{c} x \\ y \\ \end{array} \right] = \left[ \begin{array}{c} 35 \\ 94 \\ \end{array} \right] $$ 
<p></p>
<center> A**X** = B </center>
<p> </p>
<center> A<sup>-1 </sup>A**X** = A<sup>-1</sup>B  </center>
<p> </p>

<center>**X** = A<sup>-1</sup>B </center>

In [2]:
import numpy as np 

In [3]:
# Defining matrixes
A = np.matrix([[1,1], [2,4]])
B = np.matrix([[35], [94]])

In [5]:
print(A)

[[1 1]
 [2 4]]


In [6]:
print(B)

[[35]
 [94]]


In [7]:
# Taking inverse of A 
# Using numpy linear algebra function linalg.inv()
# More Infor at http://docs.scipy.org/doc/numpy-1.10.1/reference/routines.linalg.html
A_inverse = np.linalg.inv(A)

In [8]:
print(A_inverse)

[[ 2.  -0.5]
 [-1.   0.5]]


In [9]:
# Solving for X
X = A_inverse * B 

In [10]:
print(X)

[[23.]
 [12.]]


x = 23 and y = 12