# Solving System of Linear Equations using Python - May 2020

<center> 1x + 1y = 35 </center> 
<center> 2x + 4y = 94</center> 
<p> </p> 

$$A = \left[ \begin{array}{ccc} 1 & 1 \\ 2 & 4 \\ \end{array} \right]$$ 
<p></p>
$$X = \left[ \begin{array}{c} x \\ y \\ \end{array} \right]  $$ 
<p></p>
$$B = \left[ \begin{array}{c} 35 \\ 94 \\ \end{array} \right]$$
<p></p>
$$\left[ \begin{array}{ccc} 1 & 1 \\ 2 & 4 \\ \end{array} \right]\left[ \begin{array}{c} x \\ y \\ \end{array} \right] = \left[ \begin{array}{c} 35 \\ 94 \\ \end{array} \right] $$ 
<p></p>
<center> AX = B </center>
<p> </p>
<center> A<sup>-1 </sup>AX = A<sup>-1</sup>B  </center>
<p> </p>

<center>X = A<sup>-1</sup>B </center>

In [2]:
import numpy as np 

In [26]:
# Defining matrices
A = np.matrix([[1,1], [2,4]])
B = np.matrix([[35], [94]])

In [27]:
print(A)

[[1 1]
 [2 4]]


In [28]:
print(B)

[[35]
 [94]]


In [29]:
# Taking inverse of A 
# Using numpy linear algebra function linalg.inv()
# More Infor at http://docs.scipy.org/doc/numpy-1.10.1/reference/routines.linalg.html
A_inverse = np.linalg.inv(A)

In [30]:
print(A_inverse)

[[ 2.  -0.5]
 [-1.   0.5]]


In [31]:
# Solving for X
X = A_inverse * B 

In [32]:
print(X)

[[23.]
 [12.]]


In [33]:
x, y = X
print(x, y)

[[23.]] [[12.]]


## Another System of Linear Equation in 2 variables problem

<center> 6x - 11y = -58 </center> 
<center> 8x + y = 1 </center> 

<p> </p> 

$$A = \left[ \begin{array}{ccc} 6 & -11 \\ 8 & 1 \\ \end{array} \right]$$ 
<p></p>
$$X = \left[ \begin{array}{c} x \\ y \\ \end{array} \right]  $$ 
<p></p>
$$B = \left[ \begin{array}{c} -58 \\ 1 \\ \end{array} \right]$$
<p></p>
$$\left[ \begin{array}{ccc} 6 & -11 \\ 8 & 1 \\ \end{array} \right]\left[ \begin{array}{c} x \\ y \\ \end{array} \right] = \left[ \begin{array}{c} -58 \\ 1 \\ \end{array} \right] $$ 
<p></p>
<center> AX = B </center>
<p> </p>
<center> A<sup>-1 </sup>AX = A<sup>-1</sup>B  </center>
<p> </p>

<center>X = A<sup>-1</sup>B </center>

In [23]:
# Defining matrices
A = np.matrix([[6,-11], [8,1]])
B = np.matrix([[-58], [1]])

# Taking inverse of A 
# Using numpy linear algebra function linalg.inv()
# More Infor at http://docs.scipy.org/doc/numpy-1.10.1/reference/routines.linalg.html
A_inverse = np.linalg.inv(A)

# Solving for X
X = A_inverse * B 

# Show results
x, y = X

print("x = ",x," y = ", y )



x =  [[-0.5]]  y =  [[5.]]


## System of Linear Equation in 3 variables problem


From P.781 of Elementary and Intermediate Algebra Fifth Edition by Jerome E. Kaufman and Karen L. Schwitters

<left> 4x - 3y -2z = 5  </left> 
<p> </p> 
<left>      5y + z = -11 </left> 
<p> </p> 
<left>          3z = 12 </left> 
<p> </p> 

$$A = \left[ \begin{array}{ccc} 4 & 0 & 0 \\ 3 & 5 & 0 \\ 2 & 1 & 3 \\ \end{array} \right]$$ 
<p></p>
$$X = \left[ \begin{array}{c} x \\ y \\ z \\ \end{array} \right]$$ 
<p></p>
$$B = \left[ \begin{array}{c} 5 \\ -11 \\ 12 \\ \end{array} \right]$$ 
<p></p>
$$\left[ \begin{array}{ccc} 4 & 0 & 0 \\ 3 & 5 & 0 \\ 2 & 1 & 3 \\ \end{array} \right]
  \left[ \begin{array}{c} x \\ y \\ z \\ \end{array} \right] 
  = \left[ \begin{array}{c} 5 \\ -11 \\ 12 \\ \end{array} \right] $$ 
<p></p>

<center> AX = B </center>
<p> </p>
<center> A<sup>-1 </sup>AX = A<sup>-1</sup>B  </center>
<p> </p>

<center>X = A<sup>-1</sup>B </center>

In [24]:
# Defining matrices
A = np.matrix([[4,3,2], [0,5,1], [0,0,3]])
B = np.matrix([[-5], [-11], [12]])

# Taking inverse of A 
# Using numpy linear algebra function linalg.inv()
# More Infor at http://docs.scipy.org/doc/numpy-1.10.1/reference/routines.linalg.html
A_inverse = np.linalg.inv(A)

# Solving for X
X = A_inverse * B 

# Show results
x, y, z = X
print("x = ",x," y = ", y, " z = ", z )

x =  [[-1.]]  y =  [[-3.]]  z =  [[4.]]
